package banco;
// Generated 02/06/2023 13:27:54 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TbAluguel generated by hbm2java
 */
public class TbAluguel  implements java.io.Serializable {


     private Integer aluguelCod;
     private TbAutomovel tbAutomovel;
     private TbCliente tbCliente;
     private TbPagamento tbPagamento;
     private TbVendedor tbVendedor;
     private float aluguelPrecoTotal;
     private int aluguelQntParcelas;
     private Date aluguelDataInicio;
     private Date aluguelDataFim;
     private byte aluguelDevolvido;
     private Float aluguelKmFinal;

    public TbAluguel() {
    }

	
    public TbAluguel(TbAutomovel tbAutomovel, TbCliente tbCliente, TbPagamento tbPagamento, TbVendedor tbVendedor, float aluguelPrecoTotal, int aluguelQntParcelas, Date aluguelDataInicio, Date aluguelDataFim, byte aluguelDevolvido) {
        this.tbAutomovel = tbAutomovel;
        this.tbCliente = tbCliente;
        this.tbPagamento = tbPagamento;
        this.tbVendedor = tbVendedor;
        this.aluguelPrecoTotal = aluguelPrecoTotal;
        this.aluguelQntParcelas = aluguelQntParcelas;
        this.aluguelDataInicio = aluguelDataInicio;
        this.aluguelDataFim = aluguelDataFim;
        this.aluguelDevolvido = aluguelDevolvido;
    }
    public TbAluguel(TbAutomovel tbAutomovel, TbCliente tbCliente, TbPagamento tbPagamento, TbVendedor tbVendedor, float aluguelPrecoTotal, int aluguelQntParcelas, Date aluguelDataInicio, Date aluguelDataFim, byte aluguelDevolvido, Float aluguelKmFinal) {
       this.tbAutomovel = tbAutomovel;
       this.tbCliente = tbCliente;
       this.tbPagamento = tbPagamento;
       this.tbVendedor = tbVendedor;
       this.aluguelPrecoTotal = aluguelPrecoTotal;
       this.aluguelQntParcelas = aluguelQntParcelas;
       this.aluguelDataInicio = aluguelDataInicio;
       this.aluguelDataFim = aluguelDataFim;
       this.aluguelDevolvido = aluguelDevolvido;
       this.aluguelKmFinal = aluguelKmFinal;
    }
   
    public Integer getAluguelCod() {
        return this.aluguelCod;
    }
    
    public void setAluguelCod(Integer aluguelCod) {
        this.aluguelCod = aluguelCod;
    }
    public TbAutomovel getTbAutomovel() {
        return this.tbAutomovel;
    }
    
    public void setTbAutomovel(TbAutomovel tbAutomovel) {
        this.tbAutomovel = tbAutomovel;
    }
    public TbCliente getTbCliente() {
        return this.tbCliente;
    }
    
    public void setTbCliente(TbCliente tbCliente) {
        this.tbCliente = tbCliente;
    }
    public TbPagamento getTbPagamento() {
        return this.tbPagamento;
    }
    
    public void setTbPagamento(TbPagamento tbPagamento) {
        this.tbPagamento = tbPagamento;
    }
    public TbVendedor getTbVendedor() {
        return this.tbVendedor;
    }
    
    public void setTbVendedor(TbVendedor tbVendedor) {
        this.tbVendedor = tbVendedor;
    }
    public float getAluguelPrecoTotal() {
        return this.aluguelPrecoTotal;
    }
    
    public void setAluguelPrecoTotal(float aluguelPrecoTotal) {
        this.aluguelPrecoTotal = aluguelPrecoTotal;
    }
    public int getAluguelQntParcelas() {
        return this.aluguelQntParcelas;
    }
    
    public void setAluguelQntParcelas(int aluguelQntParcelas) {
        this.aluguelQntParcelas = aluguelQntParcelas;
    }
    public Date getAluguelDataInicio() {
        return this.aluguelDataInicio;
    }
    
    public void setAluguelDataInicio(Date aluguelDataInicio) {
        this.aluguelDataInicio = aluguelDataInicio;
    }
    public Date getAluguelDataFim() {
        return this.aluguelDataFim;
    }
    
    public void setAluguelDataFim(Date aluguelDataFim) {
        this.aluguelDataFim = aluguelDataFim;
    }
    public byte getAluguelDevolvido() {
        return this.aluguelDevolvido;
    }
    
    public void setAluguelDevolvido(byte aluguelDevolvido) {
        this.aluguelDevolvido = aluguelDevolvido;
    }
    public Float getAluguelKmFinal() {
        return this.aluguelKmFinal;
    }
    
    public void setAluguelKmFinal(Float aluguelKmFinal) {
        this.aluguelKmFinal = aluguelKmFinal;
    }




}


