package banco;
// Generated 02/06/2023 13:27:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbAutomovel generated by hbm2java
 */
public class TbAutomovel  implements java.io.Serializable {


     private String autoChassi;
     private TbAutomovelfab tbAutomovelfab;
     private String autoPlaca;
     private float autoKmInicial;
     private Set tbAluguels = new HashSet(0);
     private Set tbHistoricos = new HashSet(0);
     private Set tbVendas = new HashSet(0);

    public TbAutomovel() {
    }

	
    public TbAutomovel(String autoChassi, TbAutomovelfab tbAutomovelfab, float autoKmInicial) {
        this.autoChassi = autoChassi;
        this.tbAutomovelfab = tbAutomovelfab;
        this.autoKmInicial = autoKmInicial;
    }
    public TbAutomovel(String autoChassi, TbAutomovelfab tbAutomovelfab, String autoPlaca, float autoKmInicial, Set tbAluguels, Set tbHistoricos, Set tbVendas) {
       this.autoChassi = autoChassi;
       this.tbAutomovelfab = tbAutomovelfab;
       this.autoPlaca = autoPlaca;
       this.autoKmInicial = autoKmInicial;
       this.tbAluguels = tbAluguels;
       this.tbHistoricos = tbHistoricos;
       this.tbVendas = tbVendas;
    }
   
    public String getAutoChassi() {
        return this.autoChassi;
    }
    
    public void setAutoChassi(String autoChassi) {
        this.autoChassi = autoChassi;
    }
    public TbAutomovelfab getTbAutomovelfab() {
        return this.tbAutomovelfab;
    }
    
    public void setTbAutomovelfab(TbAutomovelfab tbAutomovelfab) {
        this.tbAutomovelfab = tbAutomovelfab;
    }
    public String getAutoPlaca() {
        return this.autoPlaca;
    }
    
    public void setAutoPlaca(String autoPlaca) {
        this.autoPlaca = autoPlaca;
    }
    public float getAutoKmInicial() {
        return this.autoKmInicial;
    }
    
    public void setAutoKmInicial(float autoKmInicial) {
        this.autoKmInicial = autoKmInicial;
    }
    public Set getTbAluguels() {
        return this.tbAluguels;
    }
    
    public void setTbAluguels(Set tbAluguels) {
        this.tbAluguels = tbAluguels;
    }
    public Set getTbHistoricos() {
        return this.tbHistoricos;
    }
    
    public void setTbHistoricos(Set tbHistoricos) {
        this.tbHistoricos = tbHistoricos;
    }
    public Set getTbVendas() {
        return this.tbVendas;
    }
    
    public void setTbVendas(Set tbVendas) {
        this.tbVendas = tbVendas;
    }




}


