package banco;
// Generated 02/06/2023 13:27:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbEmpregado generated by hbm2java
 */
public class TbEmpregado  implements java.io.Serializable {


     private Integer empCod;
     private TbCargo tbCargo;
     private TbPessoa tbPessoa;
     private float empSalario;
     private Set tbVendedors = new HashSet(0);

    public TbEmpregado() {
    }

	
    public TbEmpregado(TbCargo tbCargo, TbPessoa tbPessoa, float empSalario) {
        this.tbCargo = tbCargo;
        this.tbPessoa = tbPessoa;
        this.empSalario = empSalario;
    }
    public TbEmpregado(TbCargo tbCargo, TbPessoa tbPessoa, float empSalario, Set tbVendedors) {
       this.tbCargo = tbCargo;
       this.tbPessoa = tbPessoa;
       this.empSalario = empSalario;
       this.tbVendedors = tbVendedors;
    }
   
    public Integer getEmpCod() {
        return this.empCod;
    }
    
    public void setEmpCod(Integer empCod) {
        this.empCod = empCod;
    }
    public TbCargo getTbCargo() {
        return this.tbCargo;
    }
    
    public void setTbCargo(TbCargo tbCargo) {
        this.tbCargo = tbCargo;
    }
    public TbPessoa getTbPessoa() {
        return this.tbPessoa;
    }
    
    public void setTbPessoa(TbPessoa tbPessoa) {
        this.tbPessoa = tbPessoa;
    }
    public float getEmpSalario() {
        return this.empSalario;
    }
    
    public void setEmpSalario(float empSalario) {
        this.empSalario = empSalario;
    }
    public Set getTbVendedors() {
        return this.tbVendedors;
    }
    
    public void setTbVendedors(Set tbVendedors) {
        this.tbVendedors = tbVendedors;
    }




}


