package banco;
// Generated 06/06/2023 20:44:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbEstoque generated by hbm2java
 */
public class TbEstoque  implements java.io.Serializable {


     private Integer estoId;
     private TbFornecedorHasPeca tbFornecedorHasPeca;
     private int estoQuantidade;
     private int estoValorUni;
     private Set tbVenPecas = new HashSet(0);

    public TbEstoque() {
    }

	
    public TbEstoque(TbFornecedorHasPeca tbFornecedorHasPeca, int estoQuantidade, int estoValorUni) {
        this.tbFornecedorHasPeca = tbFornecedorHasPeca;
        this.estoQuantidade = estoQuantidade;
        this.estoValorUni = estoValorUni;
    }
    public TbEstoque(TbFornecedorHasPeca tbFornecedorHasPeca, int estoQuantidade, int estoValorUni, Set tbVenPecas) {
       this.tbFornecedorHasPeca = tbFornecedorHasPeca;
       this.estoQuantidade = estoQuantidade;
       this.estoValorUni = estoValorUni;
       this.tbVenPecas = tbVenPecas;
    }
   
    public Integer getEstoId() {
        return this.estoId;
    }
    
    public void setEstoId(Integer estoId) {
        this.estoId = estoId;
    }
    public TbFornecedorHasPeca getTbFornecedorHasPeca() {
        return this.tbFornecedorHasPeca;
    }
    
    public void setTbFornecedorHasPeca(TbFornecedorHasPeca tbFornecedorHasPeca) {
        this.tbFornecedorHasPeca = tbFornecedorHasPeca;
    }
    public int getEstoQuantidade() {
        return this.estoQuantidade;
    }
    
    public void setEstoQuantidade(int estoQuantidade) {
        this.estoQuantidade = estoQuantidade;
    }
    public int getEstoValorUni() {
        return this.estoValorUni;
    }
    
    public void setEstoValorUni(int estoValorUni) {
        this.estoValorUni = estoValorUni;
    }
    public Set getTbVenPecas() {
        return this.tbVenPecas;
    }
    
    public void setTbVenPecas(Set tbVenPecas) {
        this.tbVenPecas = tbVenPecas;
    }




}


