package banco;
// Generated 02/06/2023 13:27:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbFabricante generated by hbm2java
 */
public class TbFabricante  implements java.io.Serializable {


     private int fabCod;
     private String fabDescricao;
     private Set tbAutomovelfabs = new HashSet(0);

    public TbFabricante() {
    }

	
    public TbFabricante(int fabCod, String fabDescricao) {
        this.fabCod = fabCod;
        this.fabDescricao = fabDescricao;
    }
    public TbFabricante(int fabCod, String fabDescricao, Set tbAutomovelfabs) {
       this.fabCod = fabCod;
       this.fabDescricao = fabDescricao;
       this.tbAutomovelfabs = tbAutomovelfabs;
    }
   
    public int getFabCod() {
        return this.fabCod;
    }
    
    public void setFabCod(int fabCod) {
        this.fabCod = fabCod;
    }
    public String getFabDescricao() {
        return this.fabDescricao;
    }
    
    public void setFabDescricao(String fabDescricao) {
        this.fabDescricao = fabDescricao;
    }
    public Set getTbAutomovelfabs() {
        return this.tbAutomovelfabs;
    }
    
    public void setTbAutomovelfabs(Set tbAutomovelfabs) {
        this.tbAutomovelfabs = tbAutomovelfabs;
    }




}


