package banco;
// Generated 02/06/2023 13:27:54 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TbHistorico generated by hbm2java
 */
public class TbHistorico  implements java.io.Serializable {


     private Integer histCod;
     private TbAutomovel tbAutomovel;
     private String histTipoOcorrencia;
     private Date histData;
     private String histDescricao;

    public TbHistorico() {
    }

    public TbHistorico(TbAutomovel tbAutomovel, String histTipoOcorrencia, Date histData, String histDescricao) {
       this.tbAutomovel = tbAutomovel;
       this.histTipoOcorrencia = histTipoOcorrencia;
       this.histData = histData;
       this.histDescricao = histDescricao;
    }
   
    public Integer getHistCod() {
        return this.histCod;
    }
    
    public void setHistCod(Integer histCod) {
        this.histCod = histCod;
    }
    public TbAutomovel getTbAutomovel() {
        return this.tbAutomovel;
    }
    
    public void setTbAutomovel(TbAutomovel tbAutomovel) {
        this.tbAutomovel = tbAutomovel;
    }
    public String getHistTipoOcorrencia() {
        return this.histTipoOcorrencia;
    }
    
    public void setHistTipoOcorrencia(String histTipoOcorrencia) {
        this.histTipoOcorrencia = histTipoOcorrencia;
    }
    public Date getHistData() {
        return this.histData;
    }
    
    public void setHistData(Date histData) {
        this.histData = histData;
    }
    public String getHistDescricao() {
        return this.histDescricao;
    }
    
    public void setHistDescricao(String histDescricao) {
        this.histDescricao = histDescricao;
    }




}


