package banco;
// Generated 02/06/2023 13:27:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbModelo generated by hbm2java
 */
public class TbModelo  implements java.io.Serializable {


     private int modCod;
     private String modDescricao;
     private String modAno;
     private Set tbAutomovelfabs = new HashSet(0);

    public TbModelo() {
    }

	
    public TbModelo(int modCod, String modDescricao, String modAno) {
        this.modCod = modCod;
        this.modDescricao = modDescricao;
        this.modAno = modAno;
    }
    public TbModelo(int modCod, String modDescricao, String modAno, Set tbAutomovelfabs) {
       this.modCod = modCod;
       this.modDescricao = modDescricao;
       this.modAno = modAno;
       this.tbAutomovelfabs = tbAutomovelfabs;
    }
   
    public int getModCod() {
        return this.modCod;
    }
    
    public void setModCod(int modCod) {
        this.modCod = modCod;
    }
    public String getModDescricao() {
        return this.modDescricao;
    }
    
    public void setModDescricao(String modDescricao) {
        this.modDescricao = modDescricao;
    }
    public String getModAno() {
        return this.modAno;
    }
    
    public void setModAno(String modAno) {
        this.modAno = modAno;
    }
    public Set getTbAutomovelfabs() {
        return this.tbAutomovelfabs;
    }
    
    public void setTbAutomovelfabs(Set tbAutomovelfabs) {
        this.tbAutomovelfabs = tbAutomovelfabs;
    }




}


