package banco;
// Generated 02/06/2023 13:27:54 by Hibernate Tools 4.3.1



/**
 * TbPecasautomovel generated by hbm2java
 */
public class TbPecasautomovel  implements java.io.Serializable {


     private TbPecasautomovelId id;
     private TbAutomovelfab tbAutomovelfab;
     private TbPecas tbPecas;
     private int pecasAutoQnt;

    public TbPecasautomovel() {
    }

    public TbPecasautomovel(TbPecasautomovelId id, TbAutomovelfab tbAutomovelfab, TbPecas tbPecas, int pecasAutoQnt) {
       this.id = id;
       this.tbAutomovelfab = tbAutomovelfab;
       this.tbPecas = tbPecas;
       this.pecasAutoQnt = pecasAutoQnt;
    }
   
    public TbPecasautomovelId getId() {
        return this.id;
    }
    
    public void setId(TbPecasautomovelId id) {
        this.id = id;
    }
    public TbAutomovelfab getTbAutomovelfab() {
        return this.tbAutomovelfab;
    }
    
    public void setTbAutomovelfab(TbAutomovelfab tbAutomovelfab) {
        this.tbAutomovelfab = tbAutomovelfab;
    }
    public TbPecas getTbPecas() {
        return this.tbPecas;
    }
    
    public void setTbPecas(TbPecas tbPecas) {
        this.tbPecas = tbPecas;
    }
    public int getPecasAutoQnt() {
        return this.pecasAutoQnt;
    }
    
    public void setPecasAutoQnt(int pecasAutoQnt) {
        this.pecasAutoQnt = pecasAutoQnt;
    }




}


