package banco;
// Generated 02/06/2023 13:27:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbPecas generated by hbm2java
 */
public class TbPecas  implements java.io.Serializable {


     private Integer pecasCod;
     private String pecasDescricao;
     private float pecasPreco;
     private Set tbPecasautomovels = new HashSet(0);

    public TbPecas() {
    }

	
    public TbPecas(String pecasDescricao, float pecasPreco) {
        this.pecasDescricao = pecasDescricao;
        this.pecasPreco = pecasPreco;
    }
    public TbPecas(String pecasDescricao, float pecasPreco, Set tbPecasautomovels) {
       this.pecasDescricao = pecasDescricao;
       this.pecasPreco = pecasPreco;
       this.tbPecasautomovels = tbPecasautomovels;
    }
   
    public Integer getPecasCod() {
        return this.pecasCod;
    }
    
    public void setPecasCod(Integer pecasCod) {
        this.pecasCod = pecasCod;
    }
    public String getPecasDescricao() {
        return this.pecasDescricao;
    }
    
    public void setPecasDescricao(String pecasDescricao) {
        this.pecasDescricao = pecasDescricao;
    }
    public float getPecasPreco() {
        return this.pecasPreco;
    }
    
    public void setPecasPreco(float pecasPreco) {
        this.pecasPreco = pecasPreco;
    }
    public Set getTbPecasautomovels() {
        return this.tbPecasautomovels;
    }
    
    public void setTbPecasautomovels(Set tbPecasautomovels) {
        this.tbPecasautomovels = tbPecasautomovels;
    }




}


