package banco;
// Generated 02/06/2023 13:27:54 by Hibernate Tools 4.3.1



/**
 * TbPecasautomovelId generated by hbm2java
 */
public class TbPecasautomovelId  implements java.io.Serializable {


     private int pecasAutoPecasCod;
     private int pecasAutoAutoFabCod;

    public TbPecasautomovelId() {
    }

    public TbPecasautomovelId(int pecasAutoPecasCod, int pecasAutoAutoFabCod) {
       this.pecasAutoPecasCod = pecasAutoPecasCod;
       this.pecasAutoAutoFabCod = pecasAutoAutoFabCod;
    }
   
    public int getPecasAutoPecasCod() {
        return this.pecasAutoPecasCod;
    }
    
    public void setPecasAutoPecasCod(int pecasAutoPecasCod) {
        this.pecasAutoPecasCod = pecasAutoPecasCod;
    }
    public int getPecasAutoAutoFabCod() {
        return this.pecasAutoAutoFabCod;
    }
    
    public void setPecasAutoAutoFabCod(int pecasAutoAutoFabCod) {
        this.pecasAutoAutoFabCod = pecasAutoAutoFabCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TbPecasautomovelId) ) return false;
		 TbPecasautomovelId castOther = ( TbPecasautomovelId ) other; 
         
		 return (this.getPecasAutoPecasCod()==castOther.getPecasAutoPecasCod())
 && (this.getPecasAutoAutoFabCod()==castOther.getPecasAutoAutoFabCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPecasAutoPecasCod();
         result = 37 * result + this.getPecasAutoAutoFabCod();
         return result;
   }   


}


