package banco;
// Generated 02/06/2023 13:27:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbSexo generated by hbm2java
 */
public class TbSexo  implements java.io.Serializable {


     private Integer sexCod;
     private String sexDescricao;
     private Set tbPessoas = new HashSet(0);

    public TbSexo() {
    }

	
    public TbSexo(String sexDescricao) {
        this.sexDescricao = sexDescricao;
    }
    public TbSexo(String sexDescricao, Set tbPessoas) {
       this.sexDescricao = sexDescricao;
       this.tbPessoas = tbPessoas;
    }
   
    public Integer getSexCod() {
        return this.sexCod;
    }
    
    public void setSexCod(Integer sexCod) {
        this.sexCod = sexCod;
    }
    public String getSexDescricao() {
        return this.sexDescricao;
    }
    
    public void setSexDescricao(String sexDescricao) {
        this.sexDescricao = sexDescricao;
    }
    public Set getTbPessoas() {
        return this.tbPessoas;
    }
    
    public void setTbPessoas(Set tbPessoas) {
        this.tbPessoas = tbPessoas;
    }




}


