package banco;
// Generated 06/06/2023 20:44:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbServico generated by hbm2java
 */
public class TbServico  implements java.io.Serializable {


     private Integer serId;
     private String serDescricao;
     private Set tbVendaSers = new HashSet(0);

    public TbServico() {
    }

	
    public TbServico(String serDescricao) {
        this.serDescricao = serDescricao;
    }
    public TbServico(String serDescricao, Set tbVendaSers) {
       this.serDescricao = serDescricao;
       this.tbVendaSers = tbVendaSers;
    }
   
    public Integer getSerId() {
        return this.serId;
    }
    
    public void setSerId(Integer serId) {
        this.serId = serId;
    }
    public String getSerDescricao() {
        return this.serDescricao;
    }
    
    public void setSerDescricao(String serDescricao) {
        this.serDescricao = serDescricao;
    }
    public Set getTbVendaSers() {
        return this.tbVendaSers;
    }
    
    public void setTbVendaSers(Set tbVendaSers) {
        this.tbVendaSers = tbVendaSers;
    }




}


