package banco;
// Generated 02/06/2023 13:27:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbVendedor generated by hbm2java
 */
public class TbVendedor  implements java.io.Serializable {


     private Integer vendedorCod;
     private TbEmpregado tbEmpregado;
     private Float vendedorComissao;
     private Set tbAluguels = new HashSet(0);
     private Set tbVendas = new HashSet(0);

    public TbVendedor() {
    }

	
    public TbVendedor(TbEmpregado tbEmpregado) {
        this.tbEmpregado = tbEmpregado;
    }
    public TbVendedor(TbEmpregado tbEmpregado, Float vendedorComissao, Set tbAluguels, Set tbVendas) {
       this.tbEmpregado = tbEmpregado;
       this.vendedorComissao = vendedorComissao;
       this.tbAluguels = tbAluguels;
       this.tbVendas = tbVendas;
    }
   
    public Integer getVendedorCod() {
        return this.vendedorCod;
    }
    
    public void setVendedorCod(Integer vendedorCod) {
        this.vendedorCod = vendedorCod;
    }
    public TbEmpregado getTbEmpregado() {
        return this.tbEmpregado;
    }
    
    public void setTbEmpregado(TbEmpregado tbEmpregado) {
        this.tbEmpregado = tbEmpregado;
    }
    public Float getVendedorComissao() {
        return this.vendedorComissao;
    }
    
    public void setVendedorComissao(Float vendedorComissao) {
        this.vendedorComissao = vendedorComissao;
    }
    public Set getTbAluguels() {
        return this.tbAluguels;
    }
    
    public void setTbAluguels(Set tbAluguels) {
        this.tbAluguels = tbAluguels;
    }
    public Set getTbVendas() {
        return this.tbVendas;
    }
    
    public void setTbVendas(Set tbVendas) {
        this.tbVendas = tbVendas;
    }




}


