package banco;
// Generated 06/06/2023 20:44:58 by Hibernate Tools 3.6.0



/**
 * TbVendaSer generated by hbm2java
 */
public class TbVendaSer  implements java.io.Serializable {


     private Integer vsId;
     private TbServico tbServico;
     private TbVenda tbVenda;
     private TbVeiculo tbVeiculo;
     private float vsValorServico;
     private Integer vsKmPercorrido;
     private Float vsValorKm;

    public TbVendaSer() {
    }

	
    public TbVendaSer(TbServico tbServico, TbVenda tbVenda, TbVeiculo tbVeiculo, float vsValorServico) {
        this.tbServico = tbServico;
        this.tbVenda = tbVenda;
        this.tbVeiculo = tbVeiculo;
        this.vsValorServico = vsValorServico;
    }
    public TbVendaSer(TbServico tbServico, TbVenda tbVenda, TbVeiculo tbVeiculo, float vsValorServico, Integer vsKmPercorrido, Float vsValorKm) {
       this.tbServico = tbServico;
       this.tbVenda = tbVenda;
       this.tbVeiculo = tbVeiculo;
       this.vsValorServico = vsValorServico;
       this.vsKmPercorrido = vsKmPercorrido;
       this.vsValorKm = vsValorKm;
    }
   
    public Integer getVsId() {
        return this.vsId;
    }
    
    public void setVsId(Integer vsId) {
        this.vsId = vsId;
    }
    public TbServico getTbServico() {
        return this.tbServico;
    }
    
    public void setTbServico(TbServico tbServico) {
        this.tbServico = tbServico;
    }
    public TbVenda getTbVenda() {
        return this.tbVenda;
    }
    
    public void setTbVenda(TbVenda tbVenda) {
        this.tbVenda = tbVenda;
    }
    public TbVeiculo getTbVeiculo() {
        return this.tbVeiculo;
    }
    
    public void setTbVeiculo(TbVeiculo tbVeiculo) {
        this.tbVeiculo = tbVeiculo;
    }
    public float getVsValorServico() {
        return this.vsValorServico;
    }
    
    public void setVsValorServico(float vsValorServico) {
        this.vsValorServico = vsValorServico;
    }
    public Integer getVsKmPercorrido() {
        return this.vsKmPercorrido;
    }
    
    public void setVsKmPercorrido(Integer vsKmPercorrido) {
        this.vsKmPercorrido = vsKmPercorrido;
    }
    public Float getVsValorKm() {
        return this.vsValorKm;
    }
    
    public void setVsValorKm(Float vsValorKm) {
        this.vsValorKm = vsValorKm;
    }




}


